add customTargeting arguments to BannerView in Dart, iOS and Android.
ko2ic/flutter_google_ad_manager pull request #19
Opened 2019-06-12 08:57 UTC by knaeckeKami

add an optional customTargeting parameter, that allows one to show personalised ads

2019-06-13 02:30 UTC, ko2ic requested changes
Thank you so much for doing this! Overall looks good.
I left some comments regarding styling and so on.
Please change it.

2019-06-13 02:30 UTC, ko2ic commented on android/src/main/kotlin/com/ko2ic/fluttergoogleadmanager/BannerView.kt
> +        val customTargeting = arguments.get("customTargeting") as? Map<*,*>;
This should be good with the following because this key is always String, 

```
        @Suppress("UNCHECKED_CAST")
        val customTargeting = arguments["customTargeting"] as? Map<String, Any>
```

Therefore, the if statement on line 87 becomes unnecessary.

2019-06-13 02:30 UTC, ko2ic commented on ios/Classes/BannerView.swift
> +        let customTargeting = argument["customTargeting"] as? Dictionary<String, Any> ?? [String: Any]()
Please in the following.

```Dictionary<String, Any>``` => ``` [String: Any]```

2019-06-13 02:30 UTC, ko2ic commented on lib/banner.dart
> +      this.customTargeting = const {}});
Is there a reason for the initial value?

2019-06-13 02:30 UTC, ko2ic commented on lib/banner.dart
> +      this.customTargeting = const {}});
In addition, put a comma at the end of the line.

```
    this.onAdViewCreated,
    this.customTargeting,
  });
```

2019-06-13 02:30 UTC, ko2ic commented on lib/banner.dart
> +      this.customTargeting});
In addition, put a comma at the end of the line.

2019-06-13 02:30 UTC, ko2ic commented on lib/banner.dart
> +        customTargeting: widget.customTargeting));
In addition, put a comma at the end of the line.

2019-06-13 09:31 UTC, knaeckeKami commented
Thanks for your contstructive criticism. I added the requested changes.

2019-06-14 06:15 UTC, merged

2019-06-14 08:45 UTC, knaeckeKami commented
Thanks for merging. I would be delighted you you make a new release, so I can stop using my fork.